# Generated by Django 3.2.7 on 2021-09-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stblCountryCodeType',
            fields=[
                ('CountryCodeID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='stblPhoneType',
            fields=[
                ('PhoneTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneType', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='tblCountryCode',
            fields=[
                ('CodeID', models.AutoField(primary_key=True, serialize=False)),
                ('CountryCode', models.CharField(max_length=16)),
                ('CountryCodeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CCType', to='api.stblcountrycodetype')),
            ],
        ),
        migrations.CreateModel(
            name='tblPhone',
            fields=[
                ('PhoneID', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneNo', models.BigIntegerField()),
                ('CodeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CC', to='api.tblcountrycode')),
                ('PhoneTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PT', to='api.stblphonetype')),
            ],
        ),
    ]
