# Generated by Django 3.2.7 on 2021-09-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblEntityType',
            fields=[
                ('EntityTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('EntityType', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='tblcountrycode',
            name='CountryCodeIDF',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CCType', to='api.stblcountrycodetype'),
        ),
        migrations.CreateModel(
            name='tblEntity',
            fields=[
                ('EntityID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=256)),
                ('ShortName', models.CharField(max_length=16)),
                ('EntityTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PT', to='api.stblentitytype')),
            ],
        ),
    ]
