# Generated by Django 3.2.7 on 2021-09-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210918_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblHeadCountType',
            fields=[
                ('HeadCountTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('HeadCountType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tblHeadCount',
            fields=[
                ('HeadCountID', models.AutoField(primary_key=True, serialize=False)),
                ('HeadCountRange', models.BigIntegerField()),
                ('HeadCountTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblheadcounttype')),
            ],
        ),
    ]
