# Generated by Django 3.2.7 on 2021-09-20 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stblphototype_tblphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblSocialMediaType',
            fields=[
                ('SocialMediaTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('SocialMediaType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tblSocialMedia',
            fields=[
                ('SocialmediaID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('SocialMediaTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblsocialmediatype')),
            ],
        ),
    ]
