# Generated by Django 3.2.7 on 2021-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stblsocialmediatype_tblsocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblCompanyType',
            fields=[
                ('CompanyTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stblIndustryType',
            fields=[
                ('IndustryID', models.AutoField(primary_key=True, serialize=False)),
                ('IndustryType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stblSuffixType',
            fields=[
                ('SuffixID', models.AutoField(primary_key=True, serialize=False)),
                ('SuffixType', models.CharField(max_length=30)),
            ],
        ),
    ]
