# Generated by Django 3.2.7 on 2021-09-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stblcompanytype_stblindustrytype_stblsuffixtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='stblPersonType',
            fields=[
                ('PersonTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tblPerson',
            fields=[
                ('PersonID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=256)),
                ('FirstName', models.CharField(max_length=30)),
                ('MiddleName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=2)),
                ('DOB', models.DateField()),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
                ('PersonTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblpersontype')),
                ('SuffixIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblsuffixtype')),
            ],
        ),
        migrations.CreateModel(
            name='tblEntitySocialMedia',
            fields=[
                ('EntitySocialMediaID', models.AutoField(primary_key=True, serialize=False)),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
                ('SocialMediaIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblsocialmedia')),
            ],
        ),
    ]
