# Generated by Django 3.2.7 on 2021-09-20 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stblpersontype_tblentitysocialmedia_tblperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblCompany',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('GSTINNo', models.CharField(max_length=15)),
                ('Headquarter', models.CharField(max_length=30)),
                ('WebsiteURL', models.TextField()),
                ('About', models.TextField()),
                ('Founded', models.DateField()),
                ('Specialities', models.TextField()),
                ('AnnualRevenue', models.IntegerField()),
                ('CompanyTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblcompanytype')),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
                ('HeadcountIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblheadcounttype')),
                ('IndustryIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblindustrytype')),
            ],
        ),
    ]
