# Generated by Django 3.2.7 on 2021-09-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tblcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEntityPhone',
            fields=[
                ('EntityPhoneID', models.AutoField(primary_key=True, serialize=False)),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
                ('PhoneIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblphoto')),
            ],
        ),
        migrations.CreateModel(
            name='rtblEntityEmail',
            fields=[
                ('EntityEmailID', models.AutoField(primary_key=True, serialize=False)),
                ('EmailIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblemail')),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
            ],
        ),
        migrations.CreateModel(
            name='rtblEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
                ('AddressIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tbladdress')),
                ('CompanyIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblcompany')),
                ('EntityTypeIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.stblentitytype')),
                ('PersonIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblperson')),
            ],
        ),
    ]
