# Generated by Django 3.2.7 on 2021-09-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rtblentity_rtblentityemail_tblentityphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcompany',
            name='CompanyName',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
