# Generated by Django 3.2.7 on 2021-09-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tblcompany_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblperson',
            name='FullName',
        ),
    ]
