# Generated by Django 3.2.7 on 2021-09-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_tblperson_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stblemailtype',
            name='EmailType',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='stblheadcounttype',
            name='HeadCountType',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stblsuffixtype',
            name='SuffixType',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='tblcountrycode',
            name='CountryCode',
            field=models.CharField(max_length=5),
        ),
    ]
