# Generated by Django 3.2.7 on 2021-12-08 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20211207_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblperson',
            name='CreatedAT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
