# Generated by Django 3.2.7 on 2021-12-21 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_tblperson_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblperson',
            name='CreatedAT',
        ),
        migrations.RemoveField(
            model_name='tblperson',
            name='CreatedBY',
        ),
        migrations.AddField(
            model_name='tblentity',
            name='CreatedAT',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblentity',
            name='CreatedBY',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tblperson',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblentity'),
        ),
        migrations.AlterField(
            model_name='tblperson',
            name='SuffixIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SuffixBy', to='api.stblsuffixtype'),
        ),
    ]
