# Generated by Django 3.2.7 on 2021-12-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20211221_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblperson',
            name='AddressIDF',
        ),
        migrations.RemoveField(
            model_name='tblperson',
            name='CompanyIDF',
        ),
        migrations.RemoveField(
            model_name='tblperson',
            name='EmailIDF',
        ),
        migrations.RemoveField(
            model_name='tblperson',
            name='PhoneIDF',
        ),
        migrations.AlterField(
            model_name='rtblentity',
            name='Designation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
