# Generated by Django 3.2.7 on 2021-12-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20211221_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblentityphone',
            name='PhoneIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblphone'),
        ),
    ]
