# Generated by Django 3.2.7 on 2021-12-22 04:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_tblentityphone_phoneidf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtblentity',
            name='AddressIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tbladdress'),
        ),
        migrations.AlterField(
            model_name='rtblentity',
            name='CompanyIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblcompany'),
        ),
        migrations.AlterField(
            model_name='rtblentity',
            name='PersonIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tblperson'),
        ),
        migrations.AlterField(
            model_name='tblentity',
            name='CreatedAT',
            field=models.DateTimeField(default=datetime.date(2021, 12, 22)),
        ),
    ]
