# Generated by Django 3.2.7 on 2021-12-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20211222_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblphoto',
            name='Photo',
            field=models.FileField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='rtblEntityAddress',
            fields=[
                ('EntityEmailID', models.AutoField(primary_key=True, serialize=False)),
                ('AddressIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tbladdress')),
                ('EntityIDF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity')),
            ],
        ),
    ]
