# Generated by Django 3.2.7 on 2021-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20211222_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rtblentityaddress',
            old_name='EntityEmailID',
            new_name='EntityAddessID',
        ),
        migrations.AlterField(
            model_name='tblentity',
            name='CreatedAT',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
