# Generated by Django 3.2.7 on 2021-12-23 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20211223_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblphoto',
            name='EntityTypeIDF',
        ),
        migrations.AddField(
            model_name='tblphoto',
            name='EntityIDF',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblentity'),
        ),
    ]
