# Generated by Django 3.2.7 on 2021-12-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211223_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblphoto',
            name='Photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
