# Generated by Django 3.2.7 on 2021-12-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_tblphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblphoto',
            name='Photo',
            field=models.ImageField(default='Static/avatar.jpg', upload_to='images'),
        ),
    ]
